### ISSUE TITLE
How dose "WebAssembly.Memory" work?

### ISSUE THREAD

**Issue by Becavalier** [mdn/webassembly-examples#1]
I see that you add the code below in js-api-example/memory.html, but the variable "memory" not been used in anywhere.

```javascript
var memory = new WebAssembly.Memory({initial:10, maximum:100});
```

Thanks.

**Comment by chrisdavidmills** [comment]
Have you read

https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#WebAssembly_Memory
https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API#Memory

?

These provide more details on how memory works generally, and how it is accessed from a WASM module, and JavaScript.

In this particular example, we are just showing a simple example of a constructor. No, it isn't used anywhere else. In the second link above, we show how to write to and access that memory.

It is also possible to then import that memory into a WASM module. The first link above shows how to do that.

**Comment by Becavalier** [comment]
Really helpful!! Thank you very much. It means that if we wanna import a memory object from the js side, we need to modify the wast file manually, then use "wast2wasm" tool to compile the wast into wsam binary?

**Comment by Becavalier** [comment]
There is an invitation for you, we have created a slack channel for webassembly developers from all over the world, there are someone now trying compiling python into webassembly and we really encountered some problems during this process. We really need some awesome guys like you to lead us!!

Feel free to join us: 
https://join.slack.com/webassemblyteam/shared_invite/MTk2Nzc4MjkxNjUzLTE0OTczMTQ5MDEtYmJiYTZkZDVjOA

**Comment by chrisdavidmills** [comment]
Basically, yes. You probably won't ever do this in a real app (you'd just write an app in C/C++ and then transpile it using Emscripten).

Thanks for the invite ;-) TBH, you'd be better off inviting someone like @lukewagner - he knows way more about WebAssembly than me.
