### ISSUE TITLE
please add c/c++ source code of webassembly-examples/js-api-examples/table2.wat

### ISSUE THREAD

**Issue by w276549916** [mdn/webassembly-examples#13]
actually, I don't how to use  'import'  before  compiled .  thanks!

**Comment by silmanduin66** [comment]
i also would like to see the c++ source. I think that the raw wasm is pretty useless if we can't understand which functions are inside and what they are doing

**Comment by ryanmjacobs** [comment]
Yeah, the source code would be really helpful. I'm trying to wrap my head around how `memory.buffer` is passed into WASM on `memory.wat`.

**Comment by ngzhian** [comment]
For table2.wat, you can try using [wasm-decompile](https://github.com/WebAssembly/wabt/#running-wasm-decompile) to convert .wasm into something C-like:
```
import table js_tbl:funcref;

function f_a():int {
  return 42
}

function f_b():int {
  return 83
}
```

table2.wat is initializing a table with functions that are defined in Wasm. And this example shows how to construct a Table in JS and pass it to Wasm.

**Comment by ngzhian** [comment]
@ryanmjacobs The example creates a `WebAssembly.Memory` in JS. `memory.buffer` is the underlying buffer which you can write stuff to. `WebAssembly.Memory` is passed to Wasm code via the import object, under `js.mem`, and Wasm code declares that it will need this import at this line https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/memory.wat#L2. When Wasm loads/stores to this imported memory, it is modifying this same memory. I.e.:

```
var i32 = new Uint32Array(memory.buffer);
        for (var i = 0; i < 10; i++) {
          i32[i] = i;
        }
```

Is writing to the `memory.buffer` created in JS`, which is the same memory that Wasm has imported and is reading from.

**Comment by HackerWand** [comment]
> 实际上，我不会在编译之前使用“导入”。谢谢！

Hello, do you know how to do it now? Please comment

**Comment by ngzhian** [comment]
If you look at the [wat file](https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/memory.wat) it should be clearer what the example is doing, the `i32.load` is loading from a `$ptr` local, which is a pointer into the array (really the index into the memory). `var sum = obj.instance.exports.accumulate(0, 10);` is accumulating `i32[0], i32[1]...`  (`i32` is defined here https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/memory.html#L16).

**Comment by JesseRMeyer** [comment]
Thanks.  The confusion arose due to differences between the .wat file (with variable names preserved) and the served .wasm file (decompiled into wat, so $ptr and $len were 'lost' to $var0, etc).

**Comment by caugner** [comment]
All WASM files are accompanied by WAT files, so it shouldn't be necessary to add c/c++ code for demonstration, and I'm going ahead and close this issue as wontfix.
