### ISSUE TITLE
Provide source code that you used for demos

### ISSUE THREAD

**Issue by AlexanderKozhevin** [mdn/webassembly-examples#3]
There are cool examples inside **understanding-text-format** folder.
And compiled **wasm** files. But what the source for them? Is it C code or C++. How does it look like. Because without it, demos are useless.

**Comment by chrisdavidmills** [comment]
The examples inside this directory were all written by hand; they accompany the article:

https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format

The point of this article is not to understand what C or C++ could be used to generate equivalent WASM, but how the text format itself works.

**Comment by AlexanderKozhevin** [comment]
Oh, ok.
