### ISSUE TITLE
#<Module> could not be cloned

### ISSUE THREAD

**Issue by mshavliuk** [mdn/webassembly-examples#4]
When I try to execute scripts at [this demo page](https://mdn.github.io/webassembly-examples/js-api-examples/index-compile.html) I see the next errors:
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
    at fetch.then.then.then.mod (https://mdn.github.io/webassembly-examples/js-api-examples/index-compile.html:19:16)
    at <anonymous>
fetch.then.then.then.mod @ index-compile.html:19
Promise resolved (async)
(anonymous) @ index-compile.html:18
```

My browser is Chrome 62.0.3202.89

**Comment by lukewagner** [comment]
Chrome hasn't implemented this yet.

**Comment by JianmingXia** [comment]
What browser support?

**Comment by Kagami** [comment]
It's behind the `WebAssembly structured cloning support` flag in latest Chrome. Seems like it's not enabled by default due to:
https://github.com/WebAssembly/design/issues/972
https://github.com/WebAssembly/design/issues/956
https://github.com/WebAssembly/design/issues/1048

Kinda embarassing that MDN recommends to cache WebAssembly in [docs](https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules) while this is not fully managed yet and seems to work only in FF…

**Comment by chrisdavidmills** [comment]
@lukewagner what do you think we should do about this?

**Comment by lukewagner** [comment]
The Chrome folks did have objections, initially, but I think those have been addressed (by restricting where a `Module` can be `postMessage`d too), so I'm not aware of what is holding them back from enabling this feature.  @flagxor?

Edge has also shipped structured clone support and, e.g., the MDN demo works in Edge release.  Safari doesn't support structured clone, yet, though,.

Anyhow, makes sense to put up the usual compatibility chart.  When this was written, I was expecting structured cloning to ship in all browsers' initial wasm release, but that didn't end up happening.

**Comment by chrisdavidmills** [comment]
I've added a browser support section to the article in question:

https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules#Browser_support

I need to think about how to add this to our browser compat data repo first before creating one of the proper charts.

**Comment by caugner** [comment]
Verified that the example is now working in Chrome 117, Firefox 120 (Nightly) and Safari 17.0, i.e. I'm seeing some console output, so I'm closing this issue as resolved.

`structuredClone()` landed in Chrome 98 (Feb 2022), so this might have resolved it.
