### ISSUE TITLE
Which format is relevant?

### ISSUE THREAD

**Issue by turhn** [mdn/webassembly-examples#6]
When I check the examples, the simple add function looks like below:

```wast
(module
  (func $add (param $lhs i32) (param $rhs i32) (result i32)
    get_local $lhs
    get_local $rhs
    i32.add)
  (export "add" (func $add))
)
```

But other examples use the format below:

```wast
(module
  (func $add (param $lhs i32) (param $rhs i32) (result i32)
    (i32.add
      (get_local $lhs)
      (get_local $rhs))
  (export "add" (func $add))
)
```
For instance: https://cdn.rawgit.com/WebAssembly/sexpr-wasm-prototype/2bb13aa785be9908b95d0e2e09950b39a26004fa/demo/index.html

**Comment by lukewagner** [comment]
Both are valid syntax, the latter uses the [Folded Instructions](https://webassembly.github.io/spec/text/instructions.html#folded-instructions) syntactic sugar.  But maybe your point is that perhaps we should regularly use the sugar or not?

**Comment by turhn** [comment]
In fact, that was a question, and I got my answer. Thank you.

I didn't know it was also a valid syntax. The link I shared does not accept the syntactic sugar. That is why I got confused and thought that format with folded instruction might be deprecated.

**Comment by lukewagner** [comment]
Ah great.  Yes, I think sexpr-wasm-prototype is pretty out of date.  I'd use [wabt](https://github.com/WebAssembly/wabt/) or [binaryen](https://github.com/WebAssembly/binaryen/) instead.
