### ISSUE TITLE
Memory example doesn't show how to pass memory as an import

### ISSUE THREAD

**Issue by justinmchase** [mdn/webassembly-examples#7]
https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/memory.html#L13

So you've created a Memory instance. How can I send it as an import for instantiation?

**Comment by chrisdavidmills** [comment]
So, to be clear,

This example shows how to create a memory instance from JavaScript, and then how to access a memory instance (mem) created inside the WASM module and exported? You are saying you want to know how to import the memory instance created from JavaScript into the WASM module?

**Comment by lukewagner** [comment]
Oops, this example is a bit confusing: the memory created on line 13 isn't being passed to `memory.wasm` as an import and so the memory being viewed on line 16 is a separate memory that was created by `memory.wasm` itself as an export.  Probably [this line](https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/memory.wat#L2) should be changed to a memory *import*, with `memory` passed to `fetchAndInstantiate` and used to create the view.

**Comment by justinmchase** [comment]
I managed to figure it out on my own but yeah I have a separate module that is importing stdlib and calls malloc and it then gives me an int32 which is an address into memory it just allocated. So I need to import the same memory instance to get the value at the location of the pointer of course.

So in your example it showed how to create a memory instance but it doesn't show how to then pass it as an import when instantiating the module. This was the first time I had tried this so I wasn't completely familiar with the syntax. The example on mdn showed an object like `{ imports: {} }` which wasn't working for me. It turned out that the trick was that term `imports` was just a symbolic name for `imports go here` not an actual required field called imports.

I have my code at home if you want a more accurate example but it looked something like this:
```js
const memory = new WebAssembly.Memory({ initial: 2 })
fetch('stdlib.wasm', 'app.wasm', (err, results) => {
  if (err) return log(err)
  const { stdlib, app } = results
  const params = {
    env: { memory } // this was the key, memory goes on a module called `env`
  }
  load(stdlib, params, (err, stdlib) => {
    if (err) return log(err)
    Object.assign(params, { stdlib })
    load(app, params, (err, app) => {
      if (err) return log(err)
      app.main()
    })
  })
}
```

I then had to also import memory from a module called env as well as `malloc` and `free` from a module called stdlib. And it works!

**Comment by justinmchase** [comment]
And to be clear, for posterity, memory doesn't necessarily always have to be imported on a module called env, it can be anything. Just look at the imports of the module and you can see what its expected to be imported on, it just so happens that in my case it was expecting it to be called memory and on a module called env.

**Comment by lukewagner** [comment]
Right!  Tentatively closing since I think #8 addresses the issue.
